### PR TITLE
Bug/57 responsive font size

### PR DESCRIPTION
**Pull request by szymsza**
Frontend design improved, namely:

- `.sass` files with styles added
- Font sizes made responsive
- Homepage swipe incentive added
- Desktop navigation arrows added
- Slides sizing changed to fullscreen
- Various design details

`npm install` in `frontend` directory is required to make styles work!

### CODE REVIEW

**Review by PiechZ — DISMISSED** [review]
top

**Review by shippy — CHANGES_REQUESTED** [review]
Thanks for doing this! This doesn't appear to work after `docker-compose up --build` (which should be equivalent to `npm install`, since it does do that). It does the following:

- revert #41/#55 in favor of full-screen stretch, which I think makes it look worse - is that intentional?
- removes background styling from slide text without replacement
- the swipe incentive doesn't appear to be cut down to size
- the button content doesn't resolve to valid Unicode on my end, and the button styling doesn't appear to apply

Since we're deploying via Dockerization, I'm afraid we'll have to fix this to work in Docker, too.

**Comment by szymsza** [comment]
Thank you for the review.

I fixed the frontend nginx configuration, which prevented CSS from loading properly. This should make my changes work in Docker as well, thereby solving points 2 and 3 from your comment.

Ad 1 - I changed the image sizing because I think that displaying a 1:1 image on (usually) 16:9 phones looks odd, as you are wasting a big portion of the screen with a solid colour. But I can change this, of course, if you prefer the original. What does @PiechZ think?

Ad 4 - I will replace the character with a multiplatform one.

**Review by PiechZ — APPROVED** [review]

**Comment by PiechZ** [comment]
I´m more for full-screen stretch or rather this responsive behavior, it looks good on both PC and mainly mobile devices. @shippy @szymsza

**Comment by shippy** [comment]
@szymsza Sorry about nginx; thanks for fixing it. (I can't quite tell what you did, but everything seems to work, so yay.)

I agree that the slides look good on mobile - there's less background-image detail on the sides, so not much is lost there when it's cropped. Viewing it on my laptop, I'm noticing that a lot of the important-to-the-image detail is in the top third, which gets mercilessly cut off. What would you think about either (1) positioning the images so that they get cut off at the bottom instead of the top, or (2) restricting max-width but not height?

(I'm using `/slides/2956` to test, since there's a lot of achievements there.)

**Review by shippy — APPROVED** [review]
LGTM!

**Pull request merged**
